imports:
  - { resource: Backend/Widgets/ChartWidgets.yaml }
  - { resource: Backend/Widgets/ListOfRecordsWidgets.yaml }
  - { resource: Backend/Widgets/RssWidgets.yaml }

services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bo\CustomDashboardWidgets\:
    resource: '../Classes/*'

  dashboard.extendedButtons.extensionInformation:
    class: 'Bo\CustomDashboardWidgets\Widgets\Provider\ExtendedButtonProvider'
    arguments:
      $title: 'LLL:EXT:custom_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.extensionInformation.button.title'
      $link: 'https://github.com/o-ba/custom_dashboard_widgets'
      $target: '_blank'
      $icon: 'actions-merge'

  dashboard.widget.extensionInformation:
    class: 'Bo\CustomDashboardWidgets\Widgets\ExtensionInformationWidget'
    arguments:
      $buttonProvider: '@dashboard.extendedButtons.extensionInformation'
      $options:
        icon: 'tx-custom_dashboard_widgets-extension-icon'
        text: 'LLL:EXT:custom_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.extensionInformation.content.text'
    tags:
      -
        name: dashboard.widget
        identifier: 'extensionInformation'
        groupNames: 'custom'
        title: 'LLL:EXT:custom_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.extensionInformation.title'
        description: 'LLL:EXT:custom_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.extensionInformation.description'
        iconIdentifier: 'tx-custom_dashboard_widgets-extension-icon'
        height: 'small'
        width: 'medium'

  dashboard.widget.contribute:
    class: 'Bo\CustomDashboardWidgets\Widgets\ContributeWidget'
    arguments:
      $options:
        headline: 'LLL:EXT:custom_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.contribute.content.headline'
        author: 'LLL:EXT:custom_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.contribute.content.author'
        columns:
          -
            icon: 'tx-custom_dashboard_widgets-issue-icon'
            headline: 'LLL:EXT:custom_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.contribute.content.issue.headline'
            text: 'LLL:EXT:custom_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.contribute.content.issue.text'
            link: 'https://github.com/o-ba/custom_dashboard_widgets/issues'
          -
            icon: 'tx-custom_dashboard_widgets-merge-icon'
            headline: 'LLL:EXT:custom_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.contribute.content.pullRequest.headline'
            text: 'LLL:EXT:custom_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.contribute.content.pullRequest.text'
            link: 'https://github.com/o-ba/custom_dashboard_widgets/pulls'
    tags:
      -
        name: dashboard.widget
        identifier: 'contribute'
        groupNames: 'custom'
        title: 'LLL:EXT:custom_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.contribute.title'
        description: 'LLL:EXT:custom_dashboard_widgets/Resources/Private/Language/locallang.xlf:widgets.contribute.description'
        iconIdentifier: 'tx-custom_dashboard_widgets-extension-icon'
        height: 'large'
        width: 'medium'
